/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Andyman' at '12/24/16 2:02 AM' with Gradle 2.14.1
 *
 * @author Andyman, @date 12/24/16 2:02 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
